---

- name: "Pull images"
  command: "docker pull {{ item }}"
  with_items:
    - "quay.io/coreos/etcd:v3.2.0-rc.0"
    - "gcr.io/google_containers/hyperkube:v1.6.4"
    - "gcr.io/google_containers/pause-amd64:3.0"
    - "quay.io/calico/node:v1.2.1"
    - "quay.io/calico/cni:v1.8.3"
    - "quay.io/calico/kube-policy-controller:v0.6.0"


- name: "tag etcd locally"
  command: "docker tag quay.io/coreos/etcd:v3.2.0-rc.0 etcd:v3.2.0-rc.0"

- name: "tag hyperkube locally"
  command: "docker tag gcr.io/google_containers/hyperkube:v1.6.4 hyperkube:v1.6.4"

- name: "tag pause locally"
  command: "docker tag gcr.io/google_containers/pause-amd64:3.0 pause-amd64:3.0"

- name: "tag calico images locally"
  command: "docker tag quay.io/calico/{{ item }} {{ item }}"
  with_items:
    - "node:v1.2.1"
    - "cni:v1.8.3"
    - "kube-policy-controller:v0.6.0"

- name: "Save to images folder"
  command: "docker save {{ item }} -o {{ playbook_dir }}/images/{{ item | regex_replace(':', '.') }}.tar"
  with_items:
    - "etcd:v3.2.0-rc.0"
    - "hyperkube:v1.6.4"
    - "pause-amd64:3.0"
    - "node:v1.2.1"
    - "cni:v1.8.3"
    - "kube-policy-controller:v0.6.0"    
