---

- name: "Import docker registry image"
  command: "docker load --input {{ playbook_dir }}/roles/registry/files/registry.2.6.tar"

- name: "Start docker registry"
  command: "docker run -d -p 5000:5000 --name registry registry:2.6"

- name: "Check docker registry running"
  command: "docker inspect registry"
