language: python
python: "2.7"

dist: trusty

sudo: required

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get install -y python-netaddr python-apt wget
  - sudo pip install ansible

script:
  - ansible-playbook -i inventory/local images.yml
  - ansible-playbook -i inventory/local site.yml --extra-vars "travis_docker_bug=rw"
