sudo: required
group: travis_lts

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get install -y python python-dev python-netaddr python-apt
  - sudo pip install ansible

script:
  - ansible-playbook -i inventory/local images.yml
  - ansible-playbook -i inventory/local site.yml
  - kubectl cluster-info
  - kubectl get nodes -a
  - sleep 66
  - kubectl get serviceAccounts -n kube-system
  - kubectl get all -n kube-system -o wide
  - kubectl describe ds -n kube-system calico-node
  - docker ps -a
  - docker ps -a|grep calico-node_calico-node|cut -d" " -f 1|xargs docker logs
  - kubectl exec -ti -n kube-system calicoctl -- /calicoctl get node -o wide
  - kubectl exec -ti -n kube-system calicoctl -- /calicoctl get profiles -o wide
  - kubectl create -f test/kubernetes-dashboard.yaml
  - sleep 66
  - kubectl get pods -o wide -n kube-system
