sudo: required
dist: trusty
group: deprecated-2017Q4

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get install -y python python-dev python-netaddr python-apt wget
  - sudo pip install ansible

script:
  - ansible-playbook -i inventory/local images.yml
  - ansible-playbook -vvv -i inventory/local site.yml --extra-vars "travis_docker_bug=rw"
  - kubectl cluster-info
  - kubectl get nodes -a
  - sleep 30
  - kubectl get all -n kube-system -o wide
  - kubectl exec -ti -n kube-system calicoctl -- /calicoctl get node -o wide
  - kubectl exec -ti -n kube-system calicoctl -- /calicoctl get profiles -o wide
