language: python
python: "2.7"

sudo: required

services:
  - docker

before_install:
  - sudo apt-get install -y systemd python-netaddr python-apt
  - sudo pip install ansible

script:
  - ansible-playbook -i inventory/local images.yml
  - sudo ansible-playbook -i inventory/local site.yml
  - kubectl cluster-info
  - kubectl get nodes -a
  - kubectl get pods -n kube-system
  - sleep 6
  - kubectl create -f https://k8s.io/docs/tasks/run-application/deployment.yaml
  - sleep 13
  - kubectl get pods