---

- hosts: all
  roles:
    - role: check

- hosts: etcd-server
  roles:
    - role: etcd

- hosts: k8s-cluster
  roles:
    - role: k8s
    - role: kubelet
    - role: calico

- hosts: k8s-master
  roles:
    - role: apiserver
    - role: controller
    - role: scheduler