---

- name: "Copy docker hyperkube image"
  copy:
    src: "{{ playbook_dir }}/images/hyperkube.tar"
    dest: "{{ stage_dir }}/hyperkube.tar"

- name: "Import docker hyperkube image"
  command: "docker load --input {{ stage_dir }}/hyperkube.tar"

- name: "Copy docker pause image"
  copy:
    src: "{{ playbook_dir }}/images/pause.tar"
    dest: "{{ stage_dir }}/pause.tar"

- name: "Import docker pause image"
  command: "docker load --input {{ stage_dir }}/pause.tar"

- name: "Make k8s certificates dir"
  become: true
  file:
    path: "{{ kubelet_config_dir }}/cert"
    state: directory
    mode: 0755

- name: "Copy k8s certificates"
  copy:
    src: "{{ item }}"
    dest: "{{ kubelet_config_dir }}/cert/"
  with_items:
    - ca.key
    - ca.crt
    - kubelet.key
    - kubelet.crt
    - server.key
    - server.crt
    - server.csr

- name: "Copy kubectl from hyperkube container"
  command: "docker run --rm -v /usr/local/bin:/systembindir hyperkube /bin/cp /hyperkube /systembindir/kubectl"
