---

- name: "Copy docker hyperkube image"
  copy:
    src: "{{ playbook_dir }}/images/hyperkube.{{ hyperkube_version }}.tar"
    dest: "{{ stage_dir }}/hyperkube.{{ hyperkube_version }}.tar"

- name: "Import docker hyperkube image"
  command: "docker load --input {{ stage_dir }}/hyperkube.{{ hyperkube_version }}.tar"

- name: "Copy docker pause image"
  copy:
    src: "{{ playbook_dir }}/images/pause-amd64.{{ pause_version }}.tar"
    dest: "{{ stage_dir }}/pause-amd64.{{ pause_version }}.tar"

- name: "Import docker pause image"
  command: "docker load --input {{ stage_dir }}/pause-amd64.{{ pause_version }}.tar"

- name: "Make k8s certificates dir"
  file:
    path: "{{ kubelet_config_dir }}/cert"
    state: directory
    mode: 0755

- name: "Copy k8s certificates"
  copy:
    src: "{{ item }}"
    dest: "{{ kubelet_config_dir }}/cert/"
  with_items:
    - ca.crt
    - kubelet.key
    - kubelet.crt
    - server.key
    - server.crt

- name: "Copy kubectl from hyperkube container"
  command: "docker run --rm -v /usr/local/bin:/systembindir hyperkube:{{ hyperkube_version }} /bin/cp /hyperkube /systembindir/kubectl"
