---

- name: "Copy docker etcd image"
  copy:
    src: "{{ playbook_dir }}/images/etcd.{{ etcd_version }}.tar"
    dest: "{{ stage_dir }}/etcd.{{ etcd_version }}.tar"

- name: "Import docker etcd image"
  command: "docker load --input {{ stage_dir }}/etcd.{{ etcd_version }}.tar"

- name: "Run etcd"
  command: >
    docker run --net=host
    --name {{ etcd_container_name }}
    -d
    etcd:{{ etcd_version }}
    /usr/local/bin/etcd
    --name {{ inventory_hostname }}
    --initial-advertise-peer-urls http://{{ k8s_ip }}:{{ etcd_peer_port }} --listen-peer-urls http://0.0.0.0:{{ etcd_peer_port }}
    --advertise-client-urls http://{{ k8s_ip }}:{{ etcd_port }} --listen-client-urls http://0.0.0.0:{{ etcd_port }}
    --initial-cluster {{ inventory_hostname }}=http://{{ k8s_ip }}:{{ etcd_peer_port }}
    --initial-cluster-state new
