---

- name: "Copy calico images"
  copy:
    src: "{{ playbook_dir }}/images/{{ item }}.tar"
    dest: "{{ stage_dir }}/{{ item }}.tar"
  with_items:
    - cni
    - ctl
    - node
    - kube-policy-controller

- name: "Import calico images"
  command: "docker load --input {{ stage_dir }}/{{ item }}.tar"
  with_items:
    - cni
    - ctl
    - node
    - kube-policy-controller

- name: "Create manifest yml"
  template:
    src: "{{ item }}.j2"
    dest: "{{ stage_dir }}/{{ item }}"
  with_items:
    - calico.yaml
    - calicoctl.yaml

- name: "Copy Calico roles file"
  copy:
    src: "rbac.yaml"
    dest: "{{ stage_dir }}/rbac.yaml"

- name: "Apply Calico roles"
  command: "kubectl apply -f {{ stage_dir }}/rbac.yaml"

- name: "Apply Calico manifest"
  command: "kubectl apply -f {{ stage_dir }}/{{ item }}"
  with_items:
    - calico.yaml
    - calicoctl.yaml
