---

- name: "Create manifest yml"
  template:
    src: "{{ item }}.j2"
    dest: "{{ stage_dir }}/{{ item }}"
  with_items:
    - calico.yaml
    - calicoctl.yaml

- name: "Apply Calico manifest"
  command: "kubectl apply -f {{ stage_dir }}/{{ item }}"
  with_items:
    - calico.yaml
    - calicoctl.yaml
