---

- name: "Create apiserver yml"
  template:
    src: apiserver.yml.j2
    dest: "{{ kubelet_config_dir }}/manifests/apiserver.yml"

- name: "Create apiserver openssl conf"
  template:
    src: openssl.conf.j2
    dest: "{{ kubelet_config_dir }}/cert/openssl.conf"

- name: "Create apiserver certificate"
  command: >
    openssl x509 -req
    -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial
    -out server.crt -days 99999 -sha256 -extensions req_ext
    -extfile openssl.conf
  args:
    chdir: "{{ kubelet_config_dir }}/cert/"

- name: "Check api containers"
  command: "docker ps"

- name: "Wait for api server"
  wait_for:
    host: "{{ api_ip }}"
    port: "{{ api_ssl_port }}"
    delay: 9
